export interface EligibleContact { id: string; full_name: string; email: string; role: string; role_label: string }
export interface ConversationParticipant { id: string; user_id: string; full_name: string; role: string; role_label: string; joined_at: string; left_at: string | null; is_muted: boolean }
export interface MessageAttachment { id: string; original_name: string; mime_type: string; byte_size: number; checksum: string; download_url: string }
export interface MessageReceipt { delivered_at: string | null; seen_at: string | null }
export interface Message { id: string; conversation: string; sender: string; sender_name: string; sender_role: string; message_type: string; body: string; client_message_id: string; reply_to: string | null; sent_at: string; attachment?: MessageAttachment; delivery_state: 'SENT' | 'DELIVERED' | 'SEEN'; own_receipt: MessageReceipt | null }
export interface Conversation { id: string; conversation_type: string; subject: string; patient: string | null; patient_name: string | null; created_by: string; is_active: boolean; participants: ConversationParticipant[]; last_message: Message | null; unread_count: number; updated_at: string }
export interface CallParticipant { id: string; user_id: string; full_name: string; role: string; provider_identity: string; status: string; joined_at: string | null; left_at: string | null }
export interface CallIceCandidate { from_user: string; candidate: RTCIceCandidateInit }
export interface CallSession { id: string; conversation: string | null; patient: string | null; patient_name: string | null; initiated_by: string; initiated_by_name: string; provider: string; provider_sid: string; direction: string; status: string; initiated_at: string; ringing_at: string | null; answered_at: string | null; ended_at: string | null; failure_reason: string; offer_sdp: string | null; offer_from: string | null; answer_sdp: string | null; answer_from: string | null; ice_candidates?: CallIceCandidate[]; participants: CallParticipant[] }
