# Generated by Django 5.2.17 on 2026-08-16 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=12)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_threads_authored', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_threads', to='identity.patientguardprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_threads', to='patients.patient')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('response_type', models.CharField(choices=[('BOOLEAN', 'Yes or no'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('SINGLE_CHOICE', 'Single choice')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('sequence', models.PositiveIntegerField()),
                ('asked_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='monitoring.monitoringthread')),
            ],
            options={
                'ordering': ['sequence', 'asked_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.JSONField()),
                ('submitted_at', models.DateTimeField()),
                ('is_current', models.BooleanField(default=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_responses', to='identity.patientguardprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='monitoring.monitoringquestion')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='monitoring.monitoringresponse')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('question',), name='one_current_monitoring_response_per_question')],
            },
        ),
        migrations.AddIndex(
            model_name='monitoringthread',
            index=models.Index(fields=['patient', 'status', '-opened_at'], name='monitoring__patient_4ddb47_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoringquestion',
            constraint=models.UniqueConstraint(fields=('thread', 'sequence'), name='unique_monitoring_question_sequence'),
        ),
    ]
