import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, CheckCircle2, Pencil, Plus, ShieldAlert } from 'lucide-react'
import { useEffect, useState } from 'react'

import { AppApiError } from '../../../shared/api/errors'
import { Button } from '../../../shared/ui/actions/Button'
import { StatusBadge } from '../../../shared/ui/data-display/StatusBadge'
import { Alert } from '../../../shared/ui/feedback/Alert'
import { EmptyState } from '../../../shared/ui/feedback/EmptyState'
import { SectionLoader } from '../../../shared/ui/feedback/SectionLoader'
import { FormField } from '../../../shared/ui/forms/FormField'
import { SelectField } from '../../../shared/ui/forms/SelectField'
import { TextAreaField } from '../../../shared/ui/forms/TextAreaField'
import { PageHeader } from '../../../shared/ui/navigation/PageHeader'
import { Modal } from '../../../shared/ui/overlays/Modal'
import { createRecord, listRecords, postAction, updateRecord } from '../shared/api'
import type { VitalMetric, VitalRule, VitalRuleSet } from '../shared/types'

type Editor = 'metric' | 'rule-set' | 'rule' | 'activate' | null
const metricBlank = { code: '', name: '', unit: '', decimal_places: '1', description: '', is_active: true }
const ruleSetBlank = { name: '', version: '1', description: '' }
const ruleBlank = { metric: '', name: '', operator: 'GT', lower_value: '', upper_value: '', priority: '100', explanation: '', is_active: true }

export function ClinicalRulesPage() {
  const client = useQueryClient()
  const [selectedId, setSelectedId] = useState('')
  const [editor, setEditor] = useState<Editor>(null)
  const [editingMetric, setEditingMetric] = useState<VitalMetric | null>(null)
  const [editingSet, setEditingSet] = useState<VitalRuleSet | null>(null)
  const [editingRule, setEditingRule] = useState<VitalRule | null>(null)
  const [metricForm, setMetricForm] = useState(metricBlank)
  const [ruleSetForm, setRuleSetForm] = useState(ruleSetBlank)
  const [ruleForm, setRuleForm] = useState(ruleBlank)
  const metrics = useQuery({ queryKey: ['vital-metrics'], queryFn: () => listRecords<VitalMetric>('/vital-metrics/') })
  const ruleSets = useQuery({ queryKey: ['vital-rule-sets'], queryFn: () => listRecords<VitalRuleSet>('/vital-rule-sets/') })
  const rules = useQuery({ queryKey: ['vital-rules', selectedId], enabled: Boolean(selectedId), queryFn: () => listRecords<VitalRule>('/vital-rules/', { rule_set: selectedId }) })

  useEffect(() => {
    if (!selectedId && ruleSets.data?.[0]) setSelectedId(ruleSets.data[0].id)
  }, [ruleSets.data, selectedId])
  const selected = ruleSets.data?.find((item) => item.id === selectedId)
  const refresh = () => Promise.all([
    client.invalidateQueries({ queryKey: ['vital-metrics'] }), client.invalidateQueries({ queryKey: ['vital-rule-sets'] }), client.invalidateQueries({ queryKey: ['vital-rules', selectedId] }),
  ])
  const saveMutation = useMutation({
    mutationFn: () => {
      if (editor === 'metric') { const payload = { ...metricForm, decimal_places: Number(metricForm.decimal_places) }; return editingMetric ? updateRecord('/vital-metrics/', editingMetric.id, payload) : createRecord('/vital-metrics/', payload) }
      if (editor === 'rule-set') { const payload = { ...ruleSetForm, version: Number(ruleSetForm.version) }; return editingSet ? updateRecord('/vital-rule-sets/', editingSet.id, payload) : createRecord('/vital-rule-sets/', payload) }
      const payload = { rule_set: selectedId, metric: ruleForm.metric, name: ruleForm.name, operator: ruleForm.operator, lower_value: ruleForm.lower_value || null, upper_value: ruleForm.upper_value || null, priority: Number(ruleForm.priority), explanation: ruleForm.explanation, is_active: ruleForm.is_active }
      return editingRule ? updateRecord('/vital-rules/', editingRule.id, payload) : createRecord('/vital-rules/', payload)
    },
    onSuccess: async (saved) => {
      if (editor === 'rule-set' && !editingSet && typeof saved === 'object' && saved && 'id' in saved) setSelectedId(String(saved.id))
      setEditor(null); await refresh()
    },
  })
  const activateMutation = useMutation({
    mutationFn: () => selected?.status === 'ACTIVE' ? postAction(`/vital-rule-sets/${selected.id}/retire/`) : postAction(`/vital-rule-sets/${selected!.id}/activate/`),
    onSuccess: async () => { setEditor(null); await refresh() },
  })
  const openMetric = (item?: VitalMetric) => { saveMutation.reset(); setEditingMetric(item ?? null); setMetricForm(item ? { code: item.code, name: item.name, unit: item.unit, decimal_places: String(item.decimal_places), description: item.description, is_active: item.is_active } : metricBlank); setEditor('metric') }
  const openSet = (item?: VitalRuleSet) => { saveMutation.reset(); setEditingSet(item ?? null); setRuleSetForm(item ? { name: item.name, version: String(item.version), description: item.description } : { ...ruleSetBlank, version: String(Math.max(0, ...(ruleSets.data?.map((set) => set.version) ?? [])) + 1) }); setEditor('rule-set') }
  const openRule = (item?: VitalRule) => { saveMutation.reset(); setEditingRule(item ?? null); setRuleForm(item ? { metric: item.metric, name: item.name, operator: item.operator, lower_value: item.lower_value ?? '', upper_value: item.upper_value ?? '', priority: String(item.priority), explanation: item.explanation, is_active: item.is_active } : { ...ruleBlank, metric: metrics.data?.find((metric) => metric.is_active)?.id ?? '' }); setEditor('rule') }
  const rangeOperator = ['BETWEEN', 'OUTSIDE'].includes(ruleForm.operator)
  const upperOperator = ['LT', 'LTE', 'BETWEEN', 'OUTSIDE'].includes(ruleForm.operator)
  const lowerOperator = ['GT', 'GTE', 'BETWEEN', 'OUTSIDE'].includes(ruleForm.operator)

  return <div className="workspace-page">
    <PageHeader eyebrow="Clinical governance" title="Vital-sign analysis rules" description="Configure versioned and explainable rules. Velora never supplies or invents clinical thresholds." actions={<Button onClick={() => openSet()}><Plus size={16} /> New rule set</Button>} />
    <Alert tone="information" title="Hospital-approved values only">Every threshold must be supplied and approved by authorized clinical governance. If no active complete rule set can assess an observation, the patient status remains Unassessed—not Stable.</Alert>
    <div className="rules-layout">
      <aside className="rule-set-list section-panel"><div className="section-panel__heading"><div><p className="eyebrow">Versions</p><h2>Rule sets</h2></div></div>{ruleSets.isPending ? <SectionLoader /> : (ruleSets.data?.length ?? 0) === 0 ? <EmptyState title="No rule sets" description="Create a draft before adding clinical rules." /> : <div className="rule-set-list__items">{ruleSets.data!.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={item.id === selectedId ? 'rule-set-item rule-set-item--active' : 'rule-set-item'}><span><strong>{item.name}</strong><small>Version {item.version} · {item.rule_count} rules</small></span><StatusBadge status={item.status} /></button>)}</div>}<Button variant="secondary" fullWidth onClick={() => openSet()}><Plus size={15} /> New draft</Button></aside>
      <div className="rules-main">
        {!selected ? <section className="section-panel"><EmptyState title="Select or create a rule set" description="Rules are always grouped in a versioned draft before activation." /></section> : <>
          <section className="section-panel rule-set-header"><div><div className="rule-set-header__title"><span className="welcome-panel__icon"><ShieldAlert /></span><div><p className="eyebrow">{selected.status} configuration</p><h2>{selected.name} <small>v{selected.version}</small></h2><p>{selected.description || 'No description provided.'}</p></div></div>{selected.approved_by_name && <p className="approval-line"><CheckCircle2 size={16} /> Approved by {selected.approved_by_name}{selected.effective_from ? ` on ${new Date(selected.effective_from).toLocaleString()}` : ''}</p>}</div><div className="rule-set-header__actions">{selected.status === 'DRAFT' && <Button variant="secondary" onClick={() => openSet(selected)}><Pencil size={15} /> Edit draft</Button>}<Button variant={selected.status === 'ACTIVE' ? 'secondary' : 'primary'} disabled={selected.status === 'RETIRED'} onClick={() => setEditor('activate')}>{selected.status === 'ACTIVE' ? 'Retire active set' : 'Review & activate'}</Button></div></section>
          <section className="section-panel table-panel"><div className="section-panel__heading"><div><p className="eyebrow">Critical evaluation</p><h2>Rules in this set</h2></div>{selected.status === 'DRAFT' && <Button variant="secondary" disabled={(metrics.data?.filter((metric) => metric.is_active).length ?? 0) === 0} onClick={() => openRule()}><Plus size={15} /> Add rule</Button>}</div>{rules.isPending ? <SectionLoader /> : (rules.data?.length ?? 0) === 0 ? <EmptyState title="No rules in this draft" description="Add a metric rule with values approved by your hospital. No defaults are provided." action={selected.status === 'DRAFT' ? <Button onClick={() => openRule()}>Add first rule</Button> : undefined} /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Rule</th><th>Metric</th><th>Condition</th><th>Priority</th><th>Status</th><th /></tr></thead><tbody>{rules.data!.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.explanation}</small></td><td>{item.metric_name}<small>{item.metric_unit}</small></td><td>{item.operator_label} {item.operator === 'BETWEEN' || item.operator === 'OUTSIDE' ? `${item.lower_value} – ${item.upper_value}` : item.lower_value ?? item.upper_value}</td><td>{item.priority}</td><td><StatusBadge status={item.is_active ? 'ACTIVE' : 'INACTIVE'} /></td><td>{selected.status === 'DRAFT' && <Button variant="ghost" onClick={() => openRule(item)}><Pencil size={15} /> Edit</Button>}</td></tr>)}</tbody></table></div>}</section>
        </>}
        <section className="section-panel table-panel"><div className="section-panel__heading"><div><p className="eyebrow">Measurement vocabulary</p><h2>Vital metrics</h2></div><Button variant="ghost" onClick={() => openMetric()}><Plus size={15} /> Add metric</Button></div>{metrics.isPending ? <SectionLoader /> : (metrics.data?.length ?? 0) === 0 ? <EmptyState title="No vital metrics configured" description="Define only the measurements used by your hospital; thresholds are configured separately." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Metric</th><th>Unit</th><th>Precision</th><th>Status</th><th /></tr></thead><tbody>{metrics.data!.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{item.unit}</td><td>{item.decimal_places} decimal places</td><td><StatusBadge status={item.is_active ? 'ACTIVE' : 'INACTIVE'} /></td><td><Button variant="ghost" onClick={() => openMetric(item)}><Pencil size={15} /> Edit</Button></td></tr>)}</tbody></table></div>}</section>
      </div>
    </div>

    <Modal open={editor === 'metric'} onClose={() => setEditor(null)} title={editingMetric ? 'Edit vital metric' : 'Add vital metric'} description="A metric defines a name and unit only. It does not imply a safe range."><form onSubmit={(event) => { event.preventDefault(); saveMutation.mutate() }}><div className="form-grid"><FormField label="Code" required value={metricForm.code} onChange={(e) => setMetricForm({ ...metricForm, code: e.target.value.toUpperCase() })} /><FormField label="Metric name" required value={metricForm.name} onChange={(e) => setMetricForm({ ...metricForm, name: e.target.value })} /></div><div className="form-grid"><FormField label="Unit" required value={metricForm.unit} onChange={(e) => setMetricForm({ ...metricForm, unit: e.target.value })} /><FormField label="Decimal places" required type="number" min="0" max="4" value={metricForm.decimal_places} onChange={(e) => setMetricForm({ ...metricForm, decimal_places: e.target.value })} /></div><FormField label="Description" value={metricForm.description} onChange={(e) => setMetricForm({ ...metricForm, description: e.target.value })} /><label className="check-field"><input type="checkbox" checked={metricForm.is_active} onChange={(e) => setMetricForm({ ...metricForm, is_active: e.target.checked })} /><span><strong>Metric is active</strong></span></label>{saveMutation.error && <Alert tone="critical">{saveMutation.error instanceof AppApiError ? saveMutation.error.message : 'Unable to save metric.'}</Alert>}<div className="modal__actions"><Button type="button" variant="secondary" onClick={() => setEditor(null)}>Cancel</Button><Button type="submit" isLoading={saveMutation.isPending}>Save metric</Button></div></form></Modal>
    <Modal open={editor === 'rule-set'} onClose={() => setEditor(null)} title={editingSet ? 'Edit draft rule set' : 'Create rule-set draft'}><form onSubmit={(event) => { event.preventDefault(); saveMutation.mutate() }}><div className="form-grid"><FormField label="Rule-set name" required value={ruleSetForm.name} onChange={(e) => setRuleSetForm({ ...ruleSetForm, name: e.target.value })} /><FormField label="Version" required type="number" min="1" value={ruleSetForm.version} onChange={(e) => setRuleSetForm({ ...ruleSetForm, version: e.target.value })} /></div><TextAreaField label="Description" rows={3} value={ruleSetForm.description} onChange={(e) => setRuleSetForm({ ...ruleSetForm, description: e.target.value })} />{saveMutation.error && <Alert tone="critical">{saveMutation.error instanceof AppApiError ? saveMutation.error.message : 'Unable to save rule set.'}</Alert>}<div className="modal__actions"><Button type="button" variant="secondary" onClick={() => setEditor(null)}>Cancel</Button><Button type="submit" isLoading={saveMutation.isPending}>Save draft</Button></div></form></Modal>
    <Modal open={editor === 'rule'} onClose={() => setEditor(null)} title={editingRule ? 'Edit critical rule' : 'Add critical rule'} description="Values entered here must come from approved hospital policy."><form onSubmit={(event) => { event.preventDefault(); saveMutation.mutate() }}><SelectField label="Vital metric" required value={ruleForm.metric} onChange={(e) => setRuleForm({ ...ruleForm, metric: e.target.value })}>{metrics.data?.filter((metric) => metric.is_active).map((metric) => <option key={metric.id} value={metric.id}>{metric.name} · {metric.unit}</option>)}</SelectField><FormField label="Rule name" required value={ruleForm.name} onChange={(e) => setRuleForm({ ...ruleForm, name: e.target.value })} /><SelectField label="Critical when value is" value={ruleForm.operator} onChange={(e) => setRuleForm({ ...ruleForm, operator: e.target.value })}><option value="LT">Less than</option><option value="LTE">Less than or equal</option><option value="GT">Greater than</option><option value="GTE">Greater than or equal</option><option value="BETWEEN">Between</option><option value="OUTSIDE">Outside range</option></SelectField><div className="form-grid">{lowerOperator && <FormField label={rangeOperator ? 'Lower value' : 'Threshold value'} type="number" step="0.0001" required value={ruleForm.lower_value} onChange={(e) => setRuleForm({ ...ruleForm, lower_value: e.target.value })} />}{upperOperator && <FormField label={rangeOperator ? 'Upper value' : 'Threshold value'} type="number" step="0.0001" required value={ruleForm.upper_value} onChange={(e) => setRuleForm({ ...ruleForm, upper_value: e.target.value })} />}</div><FormField label="Priority" type="number" min="1" required value={ruleForm.priority} onChange={(e) => setRuleForm({ ...ruleForm, priority: e.target.value })} /><TextAreaField label="Explanation shown to clinicians" rows={3} required value={ruleForm.explanation} onChange={(e) => setRuleForm({ ...ruleForm, explanation: e.target.value })} /><label className="check-field"><input type="checkbox" checked={ruleForm.is_active} onChange={(e) => setRuleForm({ ...ruleForm, is_active: e.target.checked })} /><span><strong>Rule is included in evaluation</strong></span></label>{saveMutation.error && <Alert tone="critical">{saveMutation.error instanceof AppApiError ? saveMutation.error.message : 'Unable to save rule.'}</Alert>}<div className="modal__actions"><Button type="button" variant="secondary" onClick={() => setEditor(null)}>Cancel</Button><Button type="submit" isLoading={saveMutation.isPending}>Save rule</Button></div></form></Modal>
    <Modal open={editor === 'activate'} onClose={() => setEditor(null)} title={selected?.status === 'ACTIVE' ? 'Retire active rule set?' : 'Activate this rule set?'} description={selected?.status === 'ACTIVE' ? 'New vital observations will become Unassessed until another approved set is activated.' : 'Activation retires the currently active version. Historical evaluations keep their original rule snapshot.'}><div className="confirmation-content"><Activity size={34} /><p><strong>{selected?.name} v{selected?.version}</strong><br />{selected?.rule_count ?? 0} active rules will be affected.</p></div>{activateMutation.error && <Alert tone="critical">{activateMutation.error instanceof AppApiError ? activateMutation.error.message : 'Transition could not be completed.'}</Alert>}<div className="modal__actions"><Button variant="secondary" onClick={() => setEditor(null)}>Cancel</Button><Button variant={selected?.status === 'ACTIVE' ? 'danger' : 'primary'} isLoading={activateMutation.isPending} onClick={() => activateMutation.mutate()}>{selected?.status === 'ACTIVE' ? 'Retire rule set' : 'Activate approved rules'}</Button></div></Modal>
  </div>
}
