# Generated by Django 5.2.17 on 2026-08-16 03:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalHospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='CM', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('transfer_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'specialties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments_led', to='identity.staffprofile'),
        ),
        migrations.CreateModel(
            name='ClinicalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coding_system', models.CharField(default='LOCAL', max_length=32)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('coding_system', 'code'), name='unique_condition_code_per_system')],
            },
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('legal_name', models.CharField(max_length=180)),
                ('display_name', models.CharField(max_length=120)),
                ('registration_number', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='CM', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='hospital_profile_singleton_key_is_one')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('room_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hospital.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('SUPPLY', 'Supply'), ('OTHER', 'Other')], max_length=16)),
                ('quantity_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='AVAILABLE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='hospital.department')),
            ],
            options={
                'ordering': ['name', 'asset_code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_available__lte', models.F('quantity_total'))), name='resource_available_not_more_than_total')],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='AVAILABLE', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hospital.room')),
            ],
            options={
                'ordering': ['room__code', 'code'],
                'constraints': [models.UniqueConstraint(fields=('room', 'code'), name='unique_bed_code_per_room')],
            },
        ),
        migrations.CreateModel(
            name='HospitalServiceAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='AVAILABLE', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_availability', to='hospital.department')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_availability', to='hospital.servicedefinition')),
            ],
            options={
                'ordering': ['service__name', 'department__name'],
                'constraints': [models.UniqueConstraint(fields=('service', 'department'), name='unique_internal_service_department')],
            },
        ),
        migrations.CreateModel(
            name='ExternalHospitalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('external_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_capabilities', to='hospital.externalhospital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_hospital_capabilities', to='hospital.servicedefinition')),
            ],
            options={
                'ordering': ['external_hospital__name', 'service__name'],
                'constraints': [models.UniqueConstraint(fields=('external_hospital', 'service'), name='unique_external_hospital_service')],
            },
        ),
        migrations.CreateModel(
            name='ExternalSpecialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=140)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('external_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialists', to='hospital.externalhospital')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_specialists', to='hospital.specialty')),
            ],
            options={
                'ordering': ['external_hospital__name', 'full_name'],
                'constraints': [models.UniqueConstraint(fields=('external_hospital', 'full_name', 'specialty'), name='unique_external_specialist_identity')],
            },
        ),
        migrations.CreateModel(
            name='ExternalHospitalSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('external_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_capabilities', to='hospital.externalhospital')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_hospital_capabilities', to='hospital.specialty')),
            ],
            options={
                'ordering': ['external_hospital__name', 'specialty__name'],
                'constraints': [models.UniqueConstraint(fields=('external_hospital', 'specialty'), name='unique_external_hospital_specialty')],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_mappings', to='hospital.clinicalcondition')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_mappings', to='hospital.specialty')),
            ],
            options={
                'ordering': ['specialty__name', 'condition__name'],
                'constraints': [models.UniqueConstraint(fields=('specialty', 'condition'), name='unique_specialty_condition_mapping')],
            },
        ),
    ]
