# Generated by Django 5.2.17 on 2026-08-16 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['object_type', 'object_id', '-created_at'], name='audit_audit_object__88a561_idx'),
        ),
    ]
