# Generated by Django 5.2.17 on 2026-08-16 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('LIST', 'List'), ('VIEW', 'View'), ('PRINT', 'Print'), ('DOWNLOAD', 'Download'), ('TRANSMIT', 'Transmit')], max_length=12)),
                ('purpose', models.CharField(blank=True, max_length=180)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record_accesses', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'user', '-created_at'], name='audit_medic_patient_675016_idx')],
            },
        ),
    ]
