# Generated by Django 5.2.17 on 2026-08-16 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_medicalrecordaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(default='HEALTHY', max_length=24)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['service'],
            },
        ),
    ]
