# Generated by Django 5.2.17 on 2026-08-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_systemheartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordaccess',
            name='action',
            field=models.CharField(choices=[('LIST', 'List'), ('VIEW', 'View'), ('PRINT', 'Print'), ('DOWNLOAD', 'Download'), ('ATTACH', 'Attach'), ('TRANSMIT', 'Transmit')], max_length=12),
        ),
    ]
