# Generated by Django 5.2.17 on 2026-08-16 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_file', to='patients.patient'),
        ),
    ]
