# Generated by Django 5.2.17 on 2026-08-16 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0002_initial'),
        ('hospital', '0002_externalhospital_servicedefinition_specialty_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('PROGRESS', 'Progress note'), ('CONSULTATION', 'Consultation note'), ('NURSING', 'Nursing note'), ('DISCHARGE', 'Discharge note'), ('OTHER', 'Other')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SIGNED', 'Signed')], db_index=True, default='DRAFT', max_length=12)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('guardian_visibility', models.CharField(choices=[('INTERNAL', 'Clinical team only'), ('GUARDIAN', 'Visible to Patient Guard')], default='INTERNAL', max_length=12)),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='clinical_records.clinicalnote')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('care_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='patients.careepisode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_snapshot', models.CharField(max_length=80)),
                ('name_snapshot', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('CONFIRMED', 'Confirmed'), ('RESOLVED', 'Resolved'), ('ENTERED_IN_ERROR', 'Entered in error')], db_index=True, default='PROVISIONAL', max_length=20)),
                ('diagnosed_at', models.DateTimeField()),
                ('guardian_visibility', models.CharField(choices=[('INTERNAL', 'Clinical team only'), ('GUARDIAN', 'Visible to Patient Guard')], default='INTERNAL', max_length=12)),
                ('care_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='patients.careepisode')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='hospital.clinicalcondition')),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses_authored', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='patients.patient')),
            ],
            options={
                'ordering': ['-diagnosed_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical'), ('SURGICAL', 'Surgical'), ('FAMILY', 'Family'), ('SOCIAL', 'Social'), ('OTHER', 'Other')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, max_length=120)),
                ('guardian_visibility', models.CharField(choices=[('INTERNAL', 'Clinical team only'), ('GUARDIAN', 'Visible to Patient Guard')], default='INTERNAL', max_length=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_history_entries', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_history_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substance', models.CharField(max_length=140)),
                ('reaction', models.CharField(blank=True, max_length=240)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('UNKNOWN', 'Unknown')], max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('ENTERED_IN_ERROR', 'Entered in error')], db_index=True, default='ACTIVE', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('guardian_visibility', models.CharField(choices=[('INTERNAL', 'Clinical team only'), ('GUARDIAN', 'Visible to Patient Guard')], default='INTERNAL', max_length=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergies', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergies_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'substance', 'status'), name='unique_patient_allergy_substance_status')],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('objectives', models.TextField(blank=True)),
                ('instructions', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('guardian_visibility', models.CharField(choices=[('INTERNAL', 'Clinical team only'), ('GUARDIAN', 'Visible to Patient Guard')], default='INTERNAL', max_length=12)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans_authored', to=settings.AUTH_USER_MODEL)),
                ('care_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='patients.careepisode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='patients.patient')),
            ],
            options={
                'ordering': ['-starts_on', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='treatment_plan_end_after_start')],
            },
        ),
    ]
