# Generated by Django 5.2.17 on 2026-08-16 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_externalhospital_servicedefinition_specialty_and_more'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField()),
                ('sex_at_birth', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('INTERSEX', 'Intersex'), ('NOT_RECORDED', 'Not recorded')], max_length=16)),
                ('gender_identity', models.CharField(blank=True, max_length=80)),
                ('blood_type', models.CharField(blank=True, max_length=8)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=140)),
                ('emergency_contact_phone', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('ARCHIVED', 'Archived')], db_index=True, default='REGISTERED', max_length=16)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GuardianAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='INVITED', max_length=12)),
                ('can_view_medical_file', models.BooleanField(default=True)),
                ('can_answer_monitoring', models.BooleanField(default=True)),
                ('can_decide_transfers', models.BooleanField(default=True)),
                ('can_view_billing', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_accesses_granted', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_accesses', to='identity.patientguardprofile')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_access', to='identity.invitation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_accesses', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_number', models.CharField(max_length=40, unique=True)),
                ('episode_type', models.CharField(choices=[('INPATIENT', 'Inpatient'), ('OUTPATIENT', 'Outpatient'), ('EMERGENCY', 'Emergency')], max_length=16)),
                ('admission_reason', models.TextField()),
                ('admitted_at', models.DateTimeField()),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_episodes', to='hospital.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_episodes', to='patients.patient')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientCareAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse')], max_length=12)),
                ('is_primary', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('care_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_assignments', to='patients.careepisode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_assignments', to='patients.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_assignments', to='identity.staffprofile')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status', '-created_at'], name='patients_pa_status_b4677c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardianaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('patient', 'guardian'), name='one_active_guardian_link_per_patient_guardian'),
        ),
        migrations.AddConstraint(
            model_name='careepisode',
            constraint=models.CheckConstraint(condition=models.Q(('discharged_at__isnull', True), ('discharged_at__gte', models.F('admitted_at')), _connector='OR'), name='care_episode_discharge_after_admission'),
        ),
        migrations.AddIndex(
            model_name='patientcareassignment',
            index=models.Index(fields=['staff', 'assignment_type', 'ends_at'], name='patients_pa_staff_i_dce163_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcareassignment',
            index=models.Index(fields=['patient', 'assignment_type', 'ends_at'], name='patients_pa_patient_4052bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientcareassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='care_assignment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='patientcareassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_at__isnull', True), ('is_primary', True)), fields=('patient', 'assignment_type'), name='one_active_primary_assignment_per_type'),
        ),
    ]
