import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { HelpCircle, MessageSquarePlus, Plus, XCircle } from 'lucide-react'
import { useState } from 'react'

import { AppApiError } from '../../../shared/api/errors'
import { Button } from '../../../shared/ui/actions/Button'
import { StatusBadge } from '../../../shared/ui/data-display/StatusBadge'
import { Alert } from '../../../shared/ui/feedback/Alert'
import { EmptyState } from '../../../shared/ui/feedback/EmptyState'
import { SectionLoader } from '../../../shared/ui/feedback/SectionLoader'
import { FormField } from '../../../shared/ui/forms/FormField'
import { SelectField } from '../../../shared/ui/forms/SelectField'
import { TextAreaField } from '../../../shared/ui/forms/TextAreaField'
import { PageHeader } from '../../../shared/ui/navigation/PageHeader'
import { Modal } from '../../../shared/ui/overlays/Modal'
import { addMonitoringQuestion, closeMonitoringThread, createMonitoringThread, getMonitoringThreads } from '../../monitoring/shared/api'
import type { MonitoringThread } from '../../monitoring/shared/types'
import { getGuardians, getPatients } from '../../patient-care/shared/api'

export function DoctorMonitoringPage() {
  const client = useQueryClient()
  const [threadOpen, setThreadOpen] = useState(false)
  const [questionThread, setQuestionThread] = useState<MonitoringThread | null>(null)
  const [patientId, setPatientId] = useState('')
  const [guardianId, setGuardianId] = useState('')
  const [subject, setSubject] = useState('')
  const [question, setQuestion] = useState({ prompt: '', response_type: 'BOOLEAN', options: '', due_at: '' })
  const threads = useQuery({ queryKey: ['monitoring-threads'], queryFn: () => getMonitoringThreads() })
  const patients = useQuery({ queryKey: ['patients', 'doctor'], queryFn: () => getPatients() })
  const guardians = useQuery({ queryKey: ['patient-guardians', patientId], queryFn: () => getGuardians(patientId), enabled: Boolean(patientId) })
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: ['monitoring-threads'] }), client.invalidateQueries({ queryKey: ['notifications'] })])
  const createMutation = useMutation({ mutationFn: () => createMonitoringThread({ patient: patientId, guardian: guardianId, subject }), onSuccess: async () => { setThreadOpen(false); setSubject(''); await refresh() } })
  const questionMutation = useMutation({ mutationFn: () => addMonitoringQuestion(questionThread!.id, { prompt: question.prompt, response_type: question.response_type, options: question.response_type === 'SINGLE_CHOICE' ? question.options.split(',').map((item) => item.trim()).filter(Boolean) : [], due_at: question.due_at ? new Date(question.due_at).toISOString() : null }), onSuccess: async () => { setQuestionThread(null); await refresh() } })
  const closeMutation = useMutation({ mutationFn: closeMonitoringThread, onSuccess: refresh })
  const choosePatient = (value: string) => { setPatientId(value); setGuardianId('') }
  return <div className="workspace-page"><PageHeader eyebrow="Patient monitoring" title="Monitoring conversations" description="Ask structured questions, receive Patient Guard responses, and preserve every revision." actions={<Button onClick={() => { setThreadOpen(true); setPatientId(''); setGuardianId(''); setSubject('') }}><Plus size={16} /> New monitoring thread</Button>} />{threads.isPending ? <SectionLoader /> : threads.error ? <Alert tone="critical">Monitoring threads could not be loaded.</Alert> : (threads.data?.length ?? 0) === 0 ? <section className="section-panel"><EmptyState title="No monitoring conversations" description="Create a thread for an assigned patient and authorized Patient Guard." action={<Button onClick={() => setThreadOpen(true)}>Create monitoring thread</Button>} /></section> : <div className="monitoring-list">{threads.data!.map((thread) => <article key={thread.id} className="monitoring-thread"><header><div><span className="monitoring-thread__icon"><HelpCircle /></span><div><h2>{thread.subject}</h2><p>{thread.patient_name} · {thread.guardian_name}</p></div></div><StatusBadge status={thread.status} /></header><div className="question-list">{thread.questions.length === 0 ? <p className="inline-empty">No questions added yet.</p> : thread.questions.map((item) => <section key={item.id}><div className="question-prompt"><span>{item.sequence}</span><div><strong>{item.prompt}</strong><small>{item.response_type_label}{item.due_at ? ` · Due ${new Date(item.due_at).toLocaleString()}` : ''}</small></div></div>{item.current_response ? <div className="monitoring-answer"><strong>{String(item.current_response.answer)}</strong><small>Answered by {item.current_response.guardian_name} · {new Date(item.current_response.submitted_at).toLocaleString()}</small>{item.responses.length > 1 && <span>{item.responses.length - 1} prior revision</span>}</div> : <div className="awaiting-answer">Awaiting Patient Guard response</div>}</section>)}</div><footer>{thread.status === 'OPEN' && <><Button variant="secondary" onClick={() => { setQuestionThread(thread); setQuestion({ prompt: '', response_type: 'BOOLEAN', options: '', due_at: '' }) }}><MessageSquarePlus size={15} /> Add question</Button><Button variant="ghost" onClick={() => closeMutation.mutate(thread.id)}><XCircle size={15} /> Close thread</Button></>}</footer></article>)}</div>}
    <Modal open={threadOpen} onClose={() => setThreadOpen(false)} title="Create monitoring thread" description="Only a Patient Guard authorized for this patient can receive questions."><form onSubmit={(event) => { event.preventDefault(); createMutation.mutate() }}><SelectField label="Patient" required value={patientId} onChange={(e) => choosePatient(e.target.value)}><option value="">Select assigned patient</option>{patients.data?.map((patient) => <option key={patient.id} value={patient.id}>{patient.full_name} · {patient.medical_record_number}</option>)}</SelectField><SelectField label="Patient Guard" required value={guardianId} onChange={(e) => setGuardianId(e.target.value)}><option value="">Select authorized Patient Guard</option>{guardians.data?.filter((item) => item.status === 'ACTIVE' && item.can_answer_monitoring).map((item) => <option key={item.id} value={item.guardian_profile ?? ''}>{item.full_name} · {item.relationship}</option>)}</SelectField><FormField label="Monitoring subject" required value={subject} onChange={(e) => setSubject(e.target.value)} />{createMutation.error && <Alert tone="critical">{createMutation.error instanceof AppApiError ? createMutation.error.message : 'Thread could not be created.'}</Alert>}<div className="modal__actions"><Button type="button" variant="secondary" onClick={() => setThreadOpen(false)}>Cancel</Button><Button type="submit" isLoading={createMutation.isPending}>Create thread</Button></div></form></Modal>
    <Modal open={Boolean(questionThread)} onClose={() => setQuestionThread(null)} title="Add monitoring question" description={questionThread?.subject}><form onSubmit={(event) => { event.preventDefault(); questionMutation.mutate() }}><TextAreaField label="Question" required rows={3} value={question.prompt} onChange={(e) => setQuestion({ ...question, prompt: e.target.value })} /><SelectField label="Response type" value={question.response_type} onChange={(e) => setQuestion({ ...question, response_type: e.target.value })}><option value="BOOLEAN">Yes or no</option><option value="TEXT">Text</option><option value="NUMBER">Number</option><option value="SINGLE_CHOICE">Single choice</option></SelectField>{question.response_type === 'SINGLE_CHOICE' && <FormField label="Choices" required helperText="Separate two or more choices with commas." value={question.options} onChange={(e) => setQuestion({ ...question, options: e.target.value })} />}<FormField label="Due date and time (optional)" type="datetime-local" value={question.due_at} onChange={(e) => setQuestion({ ...question, due_at: e.target.value })} />{questionMutation.error && <Alert tone="critical">{questionMutation.error instanceof AppApiError ? questionMutation.error.message : 'Question could not be added.'}</Alert>}<div className="modal__actions"><Button type="button" variant="secondary" onClick={() => setQuestionThread(null)}>Cancel</Button><Button type="submit" isLoading={questionMutation.isPending}>Send question</Button></div></form></Modal>
  </div>
}
