# Generated by Django 5.2.17 on 2026-08-16 03:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(max_length=32)),
                ('decimal_places', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VitalRuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', editable=False, max_length=12)),
                ('active_marker', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vital_rule_sets_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('operator', models.CharField(choices=[('LT', 'Less than'), ('LTE', 'Less than or equal'), ('GT', 'Greater than'), ('GTE', 'Greater than or equal'), ('BETWEEN', 'Between'), ('OUTSIDE', 'Outside range')], max_length=12)),
                ('lower_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('upper_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('explanation', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='vital_signs.vitalmetric')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='vital_signs.vitalruleset')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='vitalruleset',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_vital_rule_set_name_version'),
        ),
        migrations.AddConstraint(
            model_name='vitalrule',
            constraint=models.UniqueConstraint(fields=('rule_set', 'metric', 'name'), name='unique_rule_name_per_metric_and_set'),
        ),
        migrations.AddConstraint(
            model_name='vitalrule',
            constraint=models.CheckConstraint(condition=models.Q(('lower_value__isnull', False), ('upper_value__isnull', False), _connector='OR'), name='vital_rule_has_threshold'),
        ),
    ]
