# Generated by Django 5.2.17 on 2026-08-16 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('vital_signs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('UNASSESSED', 'Unassessed'), ('STABLE', 'Stable'), ('CRITICAL', 'Critical')], db_index=True, default='UNASSESSED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('rule_set_name_snapshot', models.CharField(blank=True, max_length=140)),
                ('rule_set_version_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('care_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vital_observations', to='patients.careepisode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_observations', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_observations_recorded', to=settings.AUTH_USER_MODEL)),
                ('rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations_analyzed', to='vital_signs.vitalruleset')),
            ],
            options={
                'ordering': ['-observed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observed_values', to='vital_signs.vitalmetric')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='vital_signs.vitalobservation')),
            ],
            options={
                'ordering': ['metric__name'],
            },
        ),
        migrations.CreateModel(
            name='VitalRuleEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched', models.BooleanField(db_index=True)),
                ('measured_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rule_name_snapshot', models.CharField(max_length=140)),
                ('metric_name_snapshot', models.CharField(max_length=120)),
                ('metric_unit_snapshot', models.CharField(max_length=32)),
                ('operator_snapshot', models.CharField(max_length=12)),
                ('lower_value_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('upper_value_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('explanation', models.CharField(max_length=400)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='vital_signs.vitalobservation')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='vital_signs.vitalrule')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='vital_signs.vitalvalue')),
            ],
            options={
                'ordering': ['rule__priority', 'rule_name_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='vitalobservation',
            index=models.Index(fields=['patient', '-observed_at'], name='vital_signs_patient_9a96a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='vitalvalue',
            constraint=models.UniqueConstraint(fields=('observation', 'metric'), name='unique_metric_per_vital_observation'),
        ),
        migrations.AddConstraint(
            model_name='vitalruleevaluation',
            constraint=models.UniqueConstraint(fields=('observation', 'value', 'rule'), name='unique_rule_evaluation_per_observed_value'),
        ),
    ]
