# Generated by Django 5.2.17 on 2026-08-25 00:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0003_vital_stability_and_standard_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcuRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('specialist_status', models.CharField(max_length=120)),
                ('icu_bed_status', models.CharField(max_length=120)),
                ('explanation', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='icu_recommendation', to='vital_signs.vitalobservation')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
