# Generated by Django 5.2.17 on 2026-08-25 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Clinical Assistant Session', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=16)),
                ('content', models.TextField()),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('raw_llm_response', models.TextField(blank=True)),
                ('validation_passed', models.BooleanField(default=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clinical_assistant.assistantsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(default='CHAT_QUERY', max_length=64)),
                ('question', models.TextField()),
                ('response_preview', models.TextField(blank=True)),
                ('recommendation_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='SUCCESS', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_audit_logs', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='clinical_assistant.assistantsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assistantsession',
            index=models.Index(fields=['user', 'patient', '-updated_at'], name='clinical_as_user_id_d4aab6_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['session', 'created_at'], name='clinical_as_session_df7add_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantauditlog',
            index=models.Index(fields=['patient', '-created_at'], name='clinical_as_patient_716ded_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantauditlog',
            index=models.Index(fields=['user', '-created_at'], name='clinical_as_user_id_593f90_idx'),
        ),
    ]
