# Generated by Django 5.2.17 on 2026-08-16 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(max_length=140)),
                ('brand_name', models.CharField(blank=True, max_length=140)),
                ('form', models.CharField(max_length=80)),
                ('strength', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['generic_name', 'brand_name', 'strength'],
                'constraints': [models.UniqueConstraint(fields=('generic_name', 'brand_name', 'form', 'strength'), name='unique_medication_catalog_entry')],
            },
        ),
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ADMINISTERED', 'Administered'), ('MISSED', 'Missed'), ('REFUSED', 'Refused'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('due_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medication_doses_actioned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDoseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('PENDING', 'Pending'), ('ADMINISTERED', 'Administered'), ('MISSED', 'Missed'), ('REFUSED', 'Refused'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('ADMINISTERED', 'Administered'), ('MISSED', 'Missed'), ('REFUSED', 'Refused'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_dose_events', to=settings.AUTH_USER_MODEL)),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='prescriptions.medicationdose')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('prescribed_at', models.DateTimeField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('clinical_instructions', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300)),
                ('care_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.careepisode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dose_unit', models.CharField(max_length=32)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('INTRAVENOUS', 'Intravenous'), ('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEOUS', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation'), ('OTHER', 'Other')], max_length=20)),
                ('frequency_display', models.CharField(max_length=120)),
                ('duration_days', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PRN', 'As needed (PRN)')], default='SCHEDULED', max_length=12)),
                ('prn_max_per_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicationdose',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='prescriptions.prescriptionitem'),
        ),
        migrations.CreateModel(
            name='DoseScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_time', models.TimeField()),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('timezone', models.CharField(max_length=64)),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_rules', to='prescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ['local_time'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status', '-prescribed_at'], name='prescriptio_patient_c5b43d_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='prescription_end_not_before_start'),
        ),
        migrations.AddIndex(
            model_name='medicationdose',
            index=models.Index(fields=['status', 'scheduled_for'], name='prescriptio_status_0bb2d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationdose',
            constraint=models.UniqueConstraint(fields=('prescription_item', 'scheduled_for'), name='unique_scheduled_dose_per_item_time'),
        ),
        migrations.AddConstraint(
            model_name='doseschedulerule',
            constraint=models.UniqueConstraint(fields=('prescription_item', 'local_time'), name='unique_schedule_time_per_prescription_item'),
        ),
    ]
