import { useQuery } from '@tanstack/react-query'
import { Activity, Database, ShieldAlert, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'

import { StatusBadge } from '../../../shared/ui/data-display/StatusBadge'
import { Alert } from '../../../shared/ui/feedback/Alert'
import { SectionLoader } from '../../../shared/ui/feedback/SectionLoader'
import { PageHeader } from '../../../shared/ui/navigation/PageHeader'
import { getSystemDashboard } from '../users/api'

export function AdminDashboardPage() {
  const query = useQuery({ queryKey: ['system-dashboard'], queryFn: getSystemDashboard, refetchInterval: 60_000 })
  const data = query.data
  return <div className="workspace-page"><PageHeader eyebrow="System administration" title="System dashboard" description="Technical health, identity and redacted security oversight without clinical-record access." actions={<Link className="button button--secondary" to="/admin/users">Manage users</Link>} />{query.isPending ? <SectionLoader /> : query.error ? <Alert tone="critical">System health could not be loaded.</Alert> : data && <><section className="metric-grid"><article className="metric-card"><span className="metric-card__icon metric-card__icon--green"><Database /></span><div><small>Database</small><strong>{data.database.healthy ? 'Healthy' : 'Unavailable'}</strong><p>{data.database.engine}</p></div></article><article className="metric-card"><span className={`metric-card__icon ${data.scheduler.healthy ? 'metric-card__icon--green' : 'metric-card__icon--amber'}`}><Activity /></span><div><small>Medication worker</small><strong>{data.scheduler.healthy ? 'Online' : 'Stale'}</strong><p>{data.scheduler.last_seen_at ? new Date(data.scheduler.last_seen_at).toLocaleString() : 'No heartbeat'}</p></div></article><article className="metric-card"><span className="metric-card__icon metric-card__icon--blue"><UsersRound /></span><div><small>Active users</small><strong>{data.users.active}</strong><p>{data.users.inactive} inactive</p></div></article><article className="metric-card"><span className="metric-card__icon metric-card__icon--red"><ShieldAlert /></span><div><small>Failed logins</small><strong>{data.security.failed_logins_24h}</strong><p>Last 24 hours</p></div></article></section><div className="dashboard-columns"><section className="section-panel"><div className="section-panel__heading"><div><p className="eyebrow">Integrations</p><h2>Configuration</h2></div></div><ul className="health-list"><li><span>SMTP email</span><StatusBadge status={data.integrations.smtp_configured ? 'ACTIVE' : 'UNAVAILABLE'} label={data.integrations.smtp_configured ? 'Configured' : 'Not configured'} /></li><li><span>Twilio Voice</span><StatusBadge status={data.integrations.twilio_configured ? 'ACTIVE' : 'UNAVAILABLE'} label={data.integrations.twilio_configured ? 'Configured' : 'Not configured'} /></li><li><span>Transfer email failures</span><strong>{data.failures.transfer_email}</strong></li><li><span>Webhook processing failures</span><strong>{data.failures.twilio_webhooks}</strong></li></ul></section><section className="section-panel"><div className="section-panel__heading"><div><p className="eyebrow">Security</p><h2>Audit activity</h2></div><Link className="table-link" to="/admin/audit">Review</Link></div><div className="admin-audit-summary"><strong>{data.security.audit_events_24h}</strong><p>audit events recorded in the last 24 hours</p></div></section></div></>}</div>
}
