# Generated by Django 5.2.17 on 2026-08-16 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=48, unique=True)),
                ('death_datetime', models.DateTimeField()),
                ('place_of_death', models.CharField(max_length=180)),
                ('primary_cause', models.TextField()),
                ('contributing_causes', models.TextField(blank=True)),
                ('manner_of_death', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=12)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('issuing_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='death_certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='death_certificates', to='patients.patient')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='death_certificates_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-death_datetime'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ISSUED')), fields=('patient',), name='one_issued_death_certificate_per_patient')],
            },
        ),
    ]
