# Generated by Django 5.2.17 on 2026-08-16 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='TWILIO', max_length=16)),
                ('provider_sid', models.CharField(blank=True, db_index=True, max_length=80)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], default='OUTBOUND', max_length=12)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RINGING', 'Ringing'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('NO_ANSWER', 'No answer'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=16)),
                ('initiated_at', models.DateTimeField()),
                ('ringing_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='CallWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_identity', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('RINGING', 'Ringing'), ('CONNECTED', 'Connected'), ('LEFT', 'Left'), ('DECLINED', 'Declined')], default='INVITED', max_length=16)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
