# Generated by Django 5.2.17 on 2026-08-16 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('messaging', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_sessions', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_sessions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='call_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='calls.callsession'),
        ),
        migrations.AddField(
            model_name='callwebhookevent',
            name='call_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='calls.callsession'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', '-initiated_at'], name='calls_calls_status_ac91d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='callparticipant',
            constraint=models.UniqueConstraint(fields=('call_session', 'user'), name='unique_call_participant'),
        ),
    ]
