# Generated by Django 5.2.17 on 2026-08-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_callsession_answer_from_callsession_answer_sdp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="ice_candidates",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
