import { useQuery } from '@tanstack/react-query'
import { CalendarDays, Pill, ShieldCheck } from 'lucide-react'

import { StatusBadge } from '../../../shared/ui/data-display/StatusBadge'
import { Alert } from '../../../shared/ui/feedback/Alert'
import { EmptyState } from '../../../shared/ui/feedback/EmptyState'
import { SectionLoader } from '../../../shared/ui/feedback/SectionLoader'
import { PageHeader } from '../../../shared/ui/navigation/PageHeader'
import { getPrescriptions } from '../../prescriptions/shared/api'

export function PatientGuardPrescriptionsPage() {
  const query = useQuery({ queryKey: ['prescriptions', 'guard'], queryFn: () => getPrescriptions() })
  return <div className="workspace-page"><PageHeader eyebrow="Medication information" title="Prescriptions" description="Active and historical prescriptions released through your Patient Guard relationship." />{query.isPending ? <SectionLoader /> : query.error ? <Alert tone="critical">Prescriptions could not be loaded.</Alert> : (query.data?.length ?? 0) === 0 ? <section className="section-panel"><EmptyState title="No prescriptions available" description="Activated Doctor prescriptions for linked patients will appear here automatically." /></section> : <div className="prescription-list">{query.data!.map((prescription) => <article key={prescription.id} className="prescription-card"><header><div><span className="prescription-card__icon"><Pill /></span><div><h2>{prescription.patient_name}</h2><p>Prescribed by {prescription.prescribed_by_name}</p></div></div><StatusBadge status={prescription.status} /></header><div className="prescription-card__meta"><span><CalendarDays /> {prescription.starts_on} to {prescription.ends_on}</span><span>{prescription.items.length} medication {prescription.items.length === 1 ? 'item' : 'items'}</span></div><div className="prescription-medications">{prescription.items.map((item) => <section key={item.id}><div><strong>{item.medication_name}</strong><span>{Number(item.dose_amount)} {item.dose_unit} · {item.route.toLowerCase()}</span></div><p>{item.frequency_display} for {item.duration_days} days</p>{item.instructions && <p><strong>Instructions:</strong> {item.instructions}</p>}<div className="schedule-chips">{item.schedule_rules.map((rule) => <span key={rule.id}>{rule.local_time.slice(0, 5)} · {rule.days_of_week.length ? rule.days_of_week.map((day) => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][day]).join(', ') : 'Daily'}</span>)}</div></section>)}</div>{prescription.clinical_instructions && <p className="prescription-instructions"><strong>Doctor instructions:</strong> {prescription.clinical_instructions}</p>}<div className="dose-summary"><span>Scheduled <strong>{prescription.dose_summary.PENDING}</strong></span><span>Administered <strong>{prescription.dose_summary.ADMINISTERED}</strong></span><span>Missed <strong>{prescription.dose_summary.MISSED}</strong></span><span>Refused <strong>{prescription.dose_summary.REFUSED}</strong></span></div><footer className="guardian-prescription-footer"><ShieldCheck size={16} /> This prescription is read-only. Contact the care team through the authorized workflow if clarification is needed.</footer></article>)}</div>}</div>
}
