# Generated by Django 5.2.17 on 2026-08-16 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_externalhospital_servicedefinition_specialty_and_more'),
        ('identity', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('clinical_summary', models.TextField()),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECOMMENDED', 'Recommendations generated'), ('PENDING_GUARDIAN', 'Pending Patient Guard'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FILE_SENT', 'Medical file sent'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('recommendation_generation', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300)),
                ('care_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='patients.careepisode')),
                ('decision_guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='identity.patientguardprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_created', to=settings.AUTH_USER_MODEL)),
                ('selected_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_transfer_requests', to='hospital.externalhospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation', models.PositiveIntegerField()),
                ('eligible', models.BooleanField(default=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rank', models.PositiveIntegerField()),
                ('matched_requirements', models.JSONField(default=list)),
                ('missing_requirements', models.JSONField(default=list)),
                ('explanation', models.TextField()),
                ('generated_at', models.DateTimeField()),
                ('rules_version', models.CharField(default='deterministic-v1', max_length=32)),
                ('external_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_recommendations', to='hospital.externalhospital')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='transfers.transferrequest')),
            ],
            options={
                'ordering': ['generation', 'rank', 'external_hospital__name'],
            },
        ),
        migrations.CreateModel(
            name='TransferDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField()),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_decisions', to='identity.patientguardprofile')),
                ('transfer_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='transfers.transferrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_type', models.CharField(choices=[('SPECIALTY', 'Specialty'), ('SERVICE', 'Service'), ('CONDITION', 'Clinical condition')], max_length=16)),
                ('label_snapshot', models.CharField(max_length=180)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requirements', to='hospital.clinicalcondition')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requirements', to='hospital.servicedefinition')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requirements', to='hospital.specialty')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='transfers.transferrequest')),
            ],
            options={
                'ordering': ['-is_mandatory', 'requirement_type', 'label_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='TransferStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECOMMENDED', 'Recommendations generated'), ('PENDING_GUARDIAN', 'Pending Patient Guard'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FILE_SENT', 'Medical file sent'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECOMMENDED', 'Recommendations generated'), ('PENDING_GUARDIAN', 'Pending Patient Guard'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FILE_SENT', 'Medical file sent'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('occurred_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_status_events', to=settings.AUTH_USER_MODEL)),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='transfers.transferrequest')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferTransmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('package_storage_key', models.CharField(max_length=300)),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('external_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_transmissions', to='hospital.externalhospital')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_transmissions_initiated', to=settings.AUTH_USER_MODEL)),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmissions', to='transfers.transferrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['patient', 'status', '-created_at'], name='transfers_t_patient_3883ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferrecommendation',
            constraint=models.UniqueConstraint(fields=('transfer_request', 'external_hospital', 'generation'), name='unique_transfer_hospital_generation'),
        ),
    ]
